<Project>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>1.0.1</InformationalVersion>
    <Authors>indoctrinatedrecluse</Authors>
    <Product>AgduBugdu Editor</Product>
    <Description>Modern, extensible, cross-platform code and text editor built with Avalonia UI</Description>
  </PropertyGroup>
</Project>
