<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgduBugdu.PluginContracts\AgduBugdu.PluginContracts.csproj" />
    <ProjectReference Include="..\AgduBugdu.Core\AgduBugdu.Core.csproj" />
  </ItemGroup>

</Project>
